name: Set up Node environment,caches and installs dependencies

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  setup:
    name: Setup Node and Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ inputs.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node Modules
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install frontend dependencies
        run: yarn
        working-directory: frontend

      - name: Install backend dependencies
        run: yarn
        working-directory: backend

      - name: Install shared dependencies
        run: yarn
        working-directory: shared
