# =========== Terraform Config =============
# This file is AUTOGENERATED - do not edit!
# ==========================================
terraform {
  required_providers {
    aws = {
      source            = "hashicorp/aws"
      version           = "~> 4.00"
    }
  }
  required_version      = ">= 0.14.9"
  cloud {
    organization        = "##ORGANISATION##"

    workspaces {
      name = "##PROJECT##-##TYPE##-pre-setup" # will be replaced in preprocessing
    }
  }
}

// Define AWS as provider
provider "aws" {
  region              = var.aws_region
  secret_key          = var.aws_secret_access_key
  access_key          = var.aws_access_key
}

# Get workspace ID
data "tfe_workspace" "workspace" {
  name         = "##PROJECT##-##TYPE##-pre-setup"
  organization = "##ORGANISATION##"
}

// Add tag to workspace
resource "null_resource" "tag_workspace" {
  triggers = {
    timestamp = timestamp()
  }
  provisioner "local-exec" {
    command = <<EOF
export WORKSPACE_ID=${data.tfe_workspace.workspace.id}
export TF_API_TOKEN=${var.tf_api_token}
curl -X POST \
https://app.terraform.io/api/v2/workspaces/$WORKSPACE_ID/relationships/tags \
-H "Content-Type: application/vnd.api+json" \
-H "Authorization: Bearer $TF_API_TOKEN" \
-d '{"data": [{"type": "tags","attributes": {"name": "##TYPE##"}}]}'
EOF
  }
}
