import {moduleConfig} from './modules/auth';

/**
 * Exports all frontend Flox configuration that is relevant to Terraform to a .env file
 * (used by apply-flox-config.sh)
 */

console.log('# ======== Terraform Flox variables ========');
console.log('# This file is AUTOGENERATED - do not edit!');
console.log('# ==========================================');
console.log()

const authOptions = moduleConfig()


console.log('# ======== Auth module options ========');
// 2FA settings
console.log(`TF_VAR_mfa_configuration=${authOptions?.useTwoFactor ? 'ON' : 'OFF'}`)

// E-mail as username settings
console.log(`TF_VAR_auto_verified_attributes=${authOptions?.emailAsUsername ? '["email"]' : '[]'}`)
console.log(`TF_VAR_username_attributes=${authOptions?.emailAsUsername ? '["email"]' : '[]'}`)

console.log()
console.log('# ======== General project options ========');
