export enum TABLES {
  FILE = 'FILE',
  IMAGE = 'IMAGE',
  LABEL = 'LABEL',
  BOUNDING_BOX = 'BOUNDING_BOX',
  USER = 'USER',
  USER_GROUP = 'USER_GROUP',
  NOTIFICATION = 'NOTIFICATION',
}
export const ALL_TABLES = [
  TABLES.FILE,
  TABLES.IMAGE,
  TABLES.LABEL,
  TABLES.BOUNDING_BOX,
  TABLES.USER,
  TABLES.USER_GROUP,
  TABLES.NOTIFICATION,
];
