# =========== Terraform Config =============
# This file is AUTOGENERATED - do not edit!
# ==========================================
terraform {
  required_providers {
    aws = {
      source            = "hashicorp/aws"
      version           = "~> 4.00"
    }
  }
  required_version      = ">= 0.14.9"
  cloud {
    organization        = "##ORGANISATION##"

    workspaces {
      tags = ["##TYPE##"]
    }
  }
}
