# =========== Terraform Config =============
# This file is AUTOGENERATED - do not edit!
# ==========================================
terraform {
  required_providers {
    aws = {
      source            = "hashicorp/aws"
      version           = "~> 4.00"
    }
  }
  required_version      = ">= 0.14.9"
  cloud {
    organization        = "polygonsoftware"

    workspaces {
      tags = ["stage"]
    }
  }
}

#// Define AWS as provider
#provider "aws" {
#  region              = var.aws_region
#  secret_key          = var.domain_manager_aws_secret_access_key
#  access_key          = var.domain_manager_aws_access_key
#}
