name: "2.3.a: Destroy staging infrastructure on merging or deletion of a staging branch"

on:
  delete:
    branches:
      - stage-**

jobs:
  destroy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Get branch name
        id: get_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Make scripts executable
        run: |
          sudo chmod +x ./scripts/support/build.sh
          sudo chmod +x ./scripts/support/destroy-system.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Validate Terraform
        working-directory: ./scripts/support
        run: terraform validate

      - name: Destroy AWS infrastructure
        id: destroy_infrastructure
        working-directory: ./scripts/support
        run: bash destroy-system.sh stage false true confirm ${{ steps.get_branch.outputs.branch }}

      - name: Delete Terraform workspaces
        run: |
          terraform workspace delete {{ steps.destroy_infrastructure.outputs.workspace_name }}-pre-setup
          terraform workspace delete {{ steps.destroy_infrastructure.outputs.workspace_name }}-parent-setup
          terraform workspace delete {{ steps.destroy_infrastructure.outputs.workspace_name }}
