name: "Auto: Label monday.com items in a dev PR as 'PR: In Review'"

on:
  pull_request:
    branches: [dev]

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      # Set status to 'PR: In Review' if base branch is not 'master' branch
      - name: "Update state of monday.com items to 'PR: In Review'"
        id: monday-state
        uses: polygon-software/action-monday-state@main
        if: ${{ github.base_ref != 'master' }}
        with:
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          multiple: true
          allow-no-item-id: true
          monday-organization: polygonsoftware
          text: ${{ github.event.pull_request.title }}
          prefix: '#'
          status-column-title: 'Item Status!'
          set-status: 'PR: In Review'

      - name: Comment PR
        uses: polygon-software/actions-comment-pull-request@v1
        if: ${{ github.base_ref != 'master' }}
        with:
          message: ${{ steps.monday-state.outputs.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
