name: "Auto: Testing"
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node Modules
        uses: actions/cache@v2.1.4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install frontend dependencies
        run: yarn
        working-directory: frontend

      - name: Install backend dependencies
        run: yarn
        working-directory: backend

      - name: Run Backend Unit Tests
        run: yarn test:unit:report
        working-directory: backend

      - name: Run Frontend Unit Tests
        run: yarn test:unit:report
        working-directory: frontend

      - name: Upload Backend Testing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-reports
          path: backend/reports

      - name: Upload Frontend Testing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-reports
          path: frontend/reports

  sonarcloud:
    name: Sonar Coverage Scan
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Backend Testing Artifacts
        uses: actions/download-artifact@v2
        with:
          name: backend-reports
          path: backend/reports

      - name: Download Frontend Testing Artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-reports
          path: frontend/reports

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
