name: Destroy AWS infrastructure

# Should only be run manually from the Actions tab
# ATTENTION: this system may destroy infrastructure seen by customers!
on:
  workflow_dispatch:
    inputs:
      mode:
        required: true
        type: choice
        description: System deployment mode
        options:
          - test
          - dev
      force:
        required: false
        type: boolean
        description: Force desctruction
        default: false
jobs:
  setup-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          sudo chmod +x ./scripts/support/build.sh
          sudo chmod +x ./scripts/support/destroy-system.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Validate Terraform
        working-directory: ./scripts/support
        run: |
          terraform validate

      - name: Destroy AWS infrastructure
        working-directory: ./scripts/support
        run: |
          bash destroy-system.sh ${{ github.event.inputs.mode }} false ${{ github.event.inputs.force }}
