name: Push to Docker Hub & deploy to AWS ECS

on:
  push:
    branches:
      - master
      - project-*

env:
  AWS_REGION: eu-central-1                   
  AWS_DOCKERHUB_TOKEN: ${{ secrets.AWS_DOCKERHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECS_KEY_SECRET }}
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Generate Repository name
        id: repo_name
        run: |
          GITHUB_REF=${{github.ref_name}}
          GITHUB_REF=${GITHUB_REF,,}
          echo ${GITHUB_REF}
          echo "::set-output name=BRANCH_NAME::${GITHUB_REF}"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      #- name: Build and push Frontend
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: frontend
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.BRANCH_NAME }}-frontend:latest
          
      #- name: Build and push Backend
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: backend
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.BRANCH_NAME }}-backend:latest
      
      ## TODO FROM HERE
      - name: Set up Load Balancer
        run: |
          VPCID=`aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query 'Vpcs[0].VpcId'`
          echo VPC ID is $VPCID
          SUBNETS=`aws ec2 describe-subnets --filters Name=vpc-id,Values=$VPCID --query 'Subnets[*].SubnetId' --output text`
          echo Subnets are $SUBNETS
          LOADBALANCER=`aws elbv2 create-load-balancer --name ${{ steps.repo_name.outputs.BRANCH_NAME }} --type network --subnets $SUBNETS --query 'LoadBalancers[0].LoadBalancerArn'`
          echo "LOADBALANCER=$LOADBALANCER" >> $GITHUB_ENV
          
      ## TO HERE
      - name: Tets
        run: |
          echo Load balancer: ${{ env.LOADBALANCER }}
      
      #- name: Deploy to ECS
      #  run: |
      #    curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
      #    docker context create ecs ecscontext --from-env
      #    docker login
      #    docker context use ecscontext
      #    docker compose -p ${{ steps.repo_name.outputs.BRANCH_NAME }} up
      #    docker context use default
      #    docker context rm ecscontext
     
# Get VPCs: aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query 'Vpcs[0].VpcId'
# Get Tasks:  aws ecs list-tasks --cluster ${{ steps.repo_name.outputs.BRANCH_NAME }}
# Get Cluster: aws ecs describe-clusters --cluster ${{ steps.repo_name.outputs.BRANCH_NAME }}

# TODO get IP: aws elbv2 describe-load-balancers --names proje-LoadB-1MSZNWBFX165J --query 'LoadBalancers[*].DNSName' --output text
