name: Push to Docker Hub & deploy to AWS ECS

on:
  push:
    branches:
      - feature-dockerTestDeployment # TODO use project branches & master

env:
  AWS_REGION: eu-central-1                   
  ECS_SERVICE: MY_ECS_SERVICE                 # TODO set this to your Amazon ECS service name
  ECS_CLUSTER: bootstrap-test                 # TODO set this to your Amazon ECS cluster name
  FRONTEND_IMAGE_NAME: full-stack-bootstrap-frontend      # TODO: ${{ github.ref_name }}-frontend
  BACKEND_IMAGE_NAME: full-stack-bootstrap-backend        # TODO: ${{ github.ref_name }}-backend
  AWS_DOCKERHUB_TOKEN: ${{ secrets.AWS_DOCKERHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          context: "./frontend"
          path: frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
      - name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          context: "./backend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest
