name: Initial AWS setup

on:
  # Should only be run manually from the Actions tab (only once!)
  workflow_dispatch:
    inputs:
      mode:
        required: true
        type: choice
        description: System deployment mode
        options:
          - test
          - live
jobs:
  setup-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        working-directory: ./scripts/2_main-setup
        run: terraform init

      - name: Set up AWS infrastructure
        working-directory: ./scripts/support
        run: sudo bash initial-aws-setup.sh ${{ github.event.inputs.mode }}
