name: Initial AWS setup

on:
  # Should only be run manually from the Actions tab (only once!)
  workflow_dispatch:
    inputs:
      mode:
        required: true
        type: choice
        description: System deployment mode
        options:
          - test
          - live
          - dev
jobs:
  setup-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: |
          sudo chmod +x ./scripts/support/build.sh
          sudo chmod +x ./scripts/aws-initial-setup/initial-aws-setup.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Validate Terraform
        working-directory: ./scripts/aws-initial-setup
        run: terraform validate

      - name: TEST init
        working-directory: ./scripts/aws-initial-setup/0_pre-setup
        run: terraform init

      - name: test file existence
        run: |
          ls
          cat ~/.terraform.d/credentials.tfrc.json

      - name: Build & set up AWS infrastructure
        working-directory: ./scripts/aws-initial-setup
        run: sudo bash initial-aws-setup.sh ${{ github.event.inputs.mode }}
