name: Merges Master into Dev on update, will open a PR if a merge conflict exists

on:
  push:
    branches:
      - master

jobs:
  merge-master-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Set Git config
        id: setup
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Merge master back to dev
        id: merge
        run: |
          git fetch --unshallow
          git checkout master
          git pull
          pr=$(gh pr create -B "dev" -t "stage: Auto-update dev from master" -b "Automatic master merge")
          pr_number=$(echo "${pr##*/}")
          echo "PR is $pr, number is $pr_number"
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/pulls/$pr_number/merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PR already exists
        id: error
        if: steps.merge.conclusion == 'failure'
        run: echo A PR from master to dev already exists!
