name: "Stage 2: Label monday.com items arriving in DEV as 'Stage 2: Master'"

on:
  push:
    branches:
      - master

jobs:
  set-status:
    name: Set monday.com Item Status
    runs-on: ubuntu-latest
    steps:
      # Set status on-dev for items that appear in a commit message in DEV
      - name: "Update state of monday.com items to 'Stage 2: Master'"
        uses: polygon-software/action-monday-state@main
        with:
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          allow-no-item-id: true
          multiple: true
          text: ${{ join(github.event.commits.*.message, ', ') }}
          prefix: '#'
          status-column-title: 'Item Status!'
          set-status: 'Stage 2: Master'

