name: "Stage 4: Overwrite Live-Environment with content from Test-Environment"

on:
  release:
    types:
    - published

jobs:
  release:
    name: "Release new LIVE Application"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make build.sh executable
        run: sudo chmod +x ./scripts/2_main-setup/build.sh

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Build & update AWS infrastructure
        working-directory: ./scripts/support
        run: sudo bash aws-update.sh test

      - name: "Update state of monday.com items to 'Stage 4: Production'"
        uses: polygon-software/action-monday-state@main
#        if: ${{ github.event.release.draft != 'true' }}
        with:
          monday-token: ${{ secrets.MONDAY_TOKEN }}
          multiple: true
          text: ${{ github.event.release.body }}
          prefix: '#'
          status-column-title: 'Item Status!'
          set-status: 'Stage 4: Production'
          allow-no-item-id: true
