name: reviewdog
on:
  push:
    branches:
      - master
      - project-soi
      - project-bigabig
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  lint-frontend:
    name: runner / eslint
    needs:
      - setup-frontend
      - setup-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: backend

      - name: Lint frontend
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          workdir: frontend

      - name: Lint frontend
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          workdir: backend
