name: reviewdog
on:
  push:
    branches:
      - master
      - project-soi
      - project-bigabig
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint frontend
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          workdir: 'frontend'
      - name: Lint frontend
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          workdir: 'backend'
