name: Reviewdog
on:
  push:
    branches:
      - master
      - project-soi
      - project-bigabig
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  setup-node:
    name: Setup Node & Dependencies
    uses: polygon-software/full-stack-bootstrap/.github/workflows/node-yarn.yml@feature-sonarCoverage
    with:
      node: 14.x

  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      - name: Lint frontend
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          eslint_flags: "--ext .js,.ts,.vue ./"
          workdir: frontend

      - name: Lint backend
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "{src,apps,libs,test}/**/*.ts"
          workdir: backend
