name: Testing
on:
  push:
    branches:
      - master
      - project-soi
      - project-bigabig
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  setup-node:
    name: Setup Node & Dependencies
    uses: ./.github/workflows/node-yarn.yml@feature-sonarCoverage
    with:
      node: 14.x

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup-node

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Backend Unit Tests
        run: yarn test:unit:report
        working-directory: backend

      - name: Run Frontend Unit Tests
        run: yarn test:unit:report
        working-directory: frontend

      - name: Upload Backend Testing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-reports
          path: backend/reports

      - name: Upload Frontend Testing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-reports
          path: frontend/reports

  sonarcloud:
    name: Sonar Coverage Scan
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Backend Testing Artifacts
        uses: actions/download-artifact@v2
        with:
          name: backend-reports
          path: backend/reports

      - name: Download Frontend Testing Artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-reports
          path: frontend/reports

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
