name: "Convert todos to issues"
on:
  push:
    branches:
      - master
      - project-soi
      - project-bigabig
jobs:
  build:
    name: Convert TODOs to Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.5
        id: "todo"
        with:
          AUTO_ASSING: true
